version: "3"
services:

  postgres:
    container_name: "postgres"
    image: postgres:15-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=promotions
    ports:
      - '5432:5432'
